# Generated by Django 4.2.16 on 2026-04-24 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('adventure', 'Adventure'), ('cultural', 'Cultural'), ('wildlife', 'Wildlife'), ('beach', 'Beach'), ('city', 'City Tour'), ('food', 'Food & Culinary'), ('photography', 'Photography'), ('wellness', 'Wellness & Spa')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('extreme', 'Extreme')], default='easy', max_length=20)),
                ('description', models.TextField()),
                ('itinerary', models.TextField(blank=True)),
                ('duration_days', models.PositiveIntegerField()),
                ('max_group_size', models.PositiveIntegerField(default=15)),
                ('min_age', models.PositiveIntegerField(default=0)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tours/')),
                ('image_url', models.URLField(blank=True)),
                ('includes', models.TextField(blank=True, help_text='Comma-separated inclusions')),
                ('excludes', models.TextField(blank=True, help_text='Comma-separated exclusions')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='destinations.destination')),
            ],
            options={
                'db_table': 'tours',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('available_spots', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_dates', to='tours.tour')),
            ],
            options={
                'db_table': 'tour_dates',
                'ordering': ['start_date'],
            },
        ),
    ]
